projects:
  netflix:
    schemaPath: src/graphql/schema.json
    includes:
      - 'y'
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: .
extensions:
  amplify:
    version: 3
